menu:
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/jlageman'}
- {icon: 'twitter', link: 'https://bsky.app/profile/jetlageman.bsky.social'}

contacts:
- { title: 'PhD student', department: 'Section Cognitive Psychology', institution: 'Vrije Universiteit Amsterdam', institution_address: 'Van der Boechorststraat 7, 1081BT Amsterdam', email: 'j.lageman@vu.nl', office: 'MF-C569'}
